version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - .env
