# Generated by Django 2.1.5 on 2019-01-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['nick', 'recipient', 'message'], name='search_line_nick_7b3004_idx'),
        ),
    ]
